# Generated by Django 4.1.7 on 2023-04-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_movie_budget_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slud',
            field=models.SlugField(default=''),
        ),
    ]
