# Generated by Django 4.1.7 on 2023-04-09 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_movie_slud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='slud',
            new_name='slug',
        ),
    ]
