# Generated by Django 4.1.7 on 2023-04-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0013_alter_actor_first_name_alter_actor_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='actor_movie', to='movie_app.actor'),
        ),
    ]
